Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
    end

    config.vm.define "mariadb" do |mariadb|
        mariadb.vm.network "public_network", ip: "192.168.1.3"
        mariadb.vm.provision "shell",
            inline: "apt update && apt -y upgrade && apt -y dist-upgrade"
        mariadb.vm.provision "shell",
            inline: "apt -y install mariadb-server mariadb-client"
  end
end