version: '3.9'
services:
  mysql: 
    build: .
    image: mariadb-cluster
    container_name: mariadb-master-01
    hostname: mariadb-master-01
    # environment:
    #   MARIADB_ROOT_PASSWORD: "mariadb"
    restart: always
    networks:
      - mysql-cluster
    ports:
      - 3306:3306
      - 4567:4567
      - 4568:4568
      - 4444:4444
networks:
  mysql-cluster:
    name: mysql-cluster
